name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # ¿No usas npm? Cambia `npm ci` por `yarn install` o `pnpm i`.
      - name: Instalar las dependencias
        run: npm install --force

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install"

      - name: Build step
        run: "npm run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: your-waiter # TODO: sustituir por el nombre del proyecto Deno Deploy
          entrypoint: server/entry.mjs
          root: dist
