name: Deploy
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Instalar las dependencias
        run: npm install --force

      - name: Construir Astro
        run: npm run build

      - name: Install step
        run: "npm install --force"

      - name: Build step
        run: "npm run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: your-waiter
          entrypoint: server/entry.mjs
          root: dist
